# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_block', models.CharField(max_length=256)),
                ('hash_prev_block', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('txid', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('receiver', models.CharField(max_length=256)),
                ('sender', models.CharField(max_length=256)),
                ('block_hash', models.CharField(max_length=256)),
            ],
        ),
    ]
